### ISSUE TITLE
Support standalone ? et module officiel HA ??

### ISSUE THREAD

**Issue by vincegre** [tmz42/heatzy#3]
Bonjour

Avez-vous prévu de pouvoir contrôler les modules Heatzy directement en local sans passer par Internet et un compte heatzy ? ce afin de se prémunir de tout problème d'internet et pour plus de confidentialité ou le système ne le permet pas ?
Pensez-vous en faire un module officiel HA ?

Merci

Vincèn

**Comment by tmz42** [comment]
Bonjour @vincegre,

Pour les pilote, le contrôle local est compliqué... les v1 ne peuvent pas fonctionner sans Cloud, les v2 stockent en revanche la programmation, et continuent à fonctionner sans cloud. Quoi qu'il en soit, il n'y a pas (actuellement du moins) d'API locale, tout se passe chez Gizwits. Je crois que des modèles Qubino existent pour les fils pilote...

J'espère à terme en faire un module officiel HA, et j'espère de même intégrer les autres modules (Flam).

**Comment by vincegre** [comment]
> Pour les pilote, le contrôle local est compliqué... les v1 ne peuvent pas fonctionner sans Cloud, les v2 stockent en revanche la programmation, et continuent à fonctionner sans cloud. Quoi qu'il en soit, il n'y a pas (actuellement du moins) d'API locale, tout se passe chez Gizwits. Je crois que des modèles Qubino existent pour les fils pilote...

Merci pour ta réponse @tmz42 et effectivement si pas d'API locale cela ne m'intéresse pas ! je ne veux pas de domotique dépendante d'éléments externes ;)
Bonne continuation ;)
